//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4330_MODEL_Project {
	
	
	public partial class About {
		
		protected System.Web.UI.WebControls.Content BodyContent;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl form1;
		
		protected System.Web.UI.WebControls.Label CustomerName;
		
		protected System.Web.UI.WebControls.Label waitTime;
		
		protected System.Web.UI.WebControls.Label jobsLeft;
		
		protected System.Web.UI.WebControls.Label queueLength;
		
		protected System.Web.UI.WebControls.Label queuePercent;
		
		protected System.Web.UI.WebControls.Label tech;
		
		protected System.Web.UI.WebControls.DropDownList queueOver;
		
		protected System.Web.UI.WebControls.Label CustomerNameMonth;
		
		protected System.Web.UI.WebControls.Label waitTimeMonth;
		
		protected System.Web.UI.WebControls.Label jobsLeftMonth;
		
		protected System.Web.UI.WebControls.Label queueLengthMonth;
		
		protected System.Web.UI.WebControls.Label queuePercentMonth;
		
		protected System.Web.UI.WebControls.Label techMonth;
	}
}
